# Generated by Django 3.2.7 on 2022-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplan',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='workplan',
            name='goal',
            field=models.CharField(max_length=50),
        ),
    ]
